# Generated by Django 2.0.5 on 2018-05-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField()),
                ('param', models.IntegerField()),
                ('dx', models.IntegerField()),
                ('dy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreepState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('type', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_team', models.IntegerField()),
                ('enemy_hero', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('facing', models.FloatField()),
                ('lvl', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('max_mana', models.IntegerField()),
                ('available1', models.BooleanField()),
                ('available2', models.BooleanField()),
                ('available3', models.BooleanField()),
                ('available4', models.BooleanField()),
                ('time_since_damage_by_hero', models.IntegerField()),
                ('time_since_damage_by_creep', models.IntegerField()),
                ('time_since_damage_by_tower', models.IntegerField()),
                ('enemy_visible', models.BooleanField()),
                ('enemy_x', models.IntegerField()),
                ('enemy_y', models.IntegerField()),
                ('enemy_facing', models.FloatField()),
                ('enemy_lvl', models.IntegerField()),
                ('enemy_damage', models.IntegerField()),
                ('enemy_hp', models.IntegerField()),
                ('enemy_max_hp', models.IntegerField()),
                ('enemy_mana', models.IntegerField()),
                ('enemy_max_mana', models.IntegerField()),
                ('tower_hp', models.IntegerField()),
                ('enemy_tower_hp', models.IntegerField()),
                ('action_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saver.Action')),
            ],
        ),
        migrations.AddField(
            model_name='creepstate',
            name='state_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saver.State'),
        ),
    ]
